# 项目相关配置
fno:
    # 文件路径 示例（ Windows配置D:/fno/uploadPath，Linux配置 /home/fno/uploadPath）
    profile: D:/crm/work/fno-uploadpath/uploadPath
# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 197944
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: fno
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    # 资源信息
    messages:
        # 国际化资源文件路径
        basename: i18n/messages
    # 文件上传
    servlet:
        multipart:
            # 单个文件大小
            max-file-size:  10MB
            # 设置总上传的文件大小
            max-request-size:  20MB
    # 服务模块
    devtools:
        restart:
            # 热部署开关
            enabled: true
    # redis 配置
    redis:
        # 地址
        #    host: asmalllion.space
        host: 127.0.0.1
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        #    password: 8596729401a
        # 连接超时时间,单位毫秒
        timeout: 5000
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 1
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
            cluster:
                refresh:
                    #20秒自动刷新一次
                    period: 20
                    adaptive: true
        jedis:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 1
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
